backend:
  name: github
  repo: raffys2k/Booklyst-repository
  branch: main
  base_url: https://api.netlifycms.org

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "books"
    label: "Books"
    folder: "content/books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Genre", name: "genre", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
